services:
  backend:
    build:
      context: ./backend
    container_name: backend-pong
    networks:
      - pong-net
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-pong
    ports:
      - "8080:80"
    networks:
      - pong-net
    depends_on:
      - backend

networks:
  pong-net:
    driver: bridge