version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
      - authentication
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "file:/usr/src/app/prisma/dev.db" 
      JWT_SECRET: "transcendence"
    volumes:
      - backend-db-data:/usr/src/app/prisma
    ports:
      - "9229:9229"  # <--- Adicione esta linha para expor a porta de depuração
      - "5555:5555"  # <--- Adicione esta linha para expor a porta do nodemon
    command: sh -c "npx prisma migrate dev && npm run dev" # <--- Adicione esta linha para rodar o nodemon
    depends_on:
      - authentication
    networks:
      - app-network

  authentication:
    build: ./authentication
    environment:
      DATABASE_URL: "file:/usr/src/app/prisma/auth.db"
      JWT_SECRET: "transcendence"
      GOOGLE_CLIENT_ID: "298539346397-imm2ctlgievdlfb7vff3pdsh2291itjk.apps.googleusercontent.com"
    ports:
      - "3000:3000"
    volumes:
      - auth-db-data:/usr/src/app/prisma
    networks:
      - app-network

volumes:
  backend-db-data:
  auth-db-data:

networks:
  app-network:
    driver: bridge