version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args: 
        - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./devops/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - user-service
      - auth-service
      - game-service
    networks:
      - app-network

  user-service:
    build: user-service
    environment:
      DATABASE_USER_URL: ${DATABASE_USER_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - user-service-prisma-data:/usr/src/app/prisma
    ports:
      - "9229:9229"
      - "5555:5555"
    depends_on:
      - auth-service
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    environment:
      DATABASE_AUTH_URL: ${DATABASE_AUTH_URL}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GAME_SERVICE_URL: ${GAME_SERVICE_URL}
      DATABASE_AUTH_POSTGRES_URL: ${DATABASE_AUTH_POSTGRES_URL}
    ports:
      - "3000:3000"
    volumes:
      - auth-prisma-data:/usr/src/app/prisma
    networks:
      - app-network

  game-service:
    build: game-service
    environment:
      DATABASE_GAME_URL: ${DATABASE_GAME_URL}
      JWT_SECRET: ${JWT_SECRET}
      BACKEND_API_URL: ${BACKEND_API_URL}
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED}
    ports:
      - "3001:3001"
      - "5556:5556"
    volumes:
      - game-service-prisma-data:/usr/src/app/prisma
      - ./devops/nginx/ssl:/usr/src/app/ssl:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user-service-prisma-data:
  auth-prisma-data:
  game-service-prisma-data: