services:
  backend: #django
    container_name: backend
    build:
      context: backend/
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      DATABASE: ${DATABASE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db: #postgres
    container_name: db
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-volume:/var/lib/postgresql/data/
    restart: always
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5

  frontend:
    container_name: frontend
    build:
      context: frontend/
    ports:
      - "3000:80"

networks:
  network:
    driver: bridge

volumes:
  db-volume:
