version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
      - authentication
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "file:/usr/src/app/prisma/dev.db"
      JWT_SECRET: "transcendence"
    volumes:
      - ./prisma-data/backend:/usr/src/app/prisma
    ports:
      # Debug
      - "9229:9229"
      # Prisma Studio
      - "5555:5555"
    depends_on:
      - authentication
    networks:
      - app-network

  authentication:
    build: ./authentication
    environment:
      DATABASE_URL: "file:/usr/src/app/prisma/auth.db"
      JWT_SECRET: "transcendence"
      GOOGLE_CLIENT_ID: "298539346397-imm2ctlgievdlfb7vff3pdsh2291itjk.apps.googleusercontent.com"
    ports:
      - "3000:3000"
    volumes:
      - ./prisma-data/auth:/usr/src/app/prisma
    networks:
      - app-network

networks:
  app-network:
    driver: bridge