version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - auth-service
      - game-service
    networks:
      - app-network

  user-service:
    build: user-service
    environment:
      DATABASE_URL: "file:/usr/src/app/prisma/dev.db"
      JWT_SECRET: "transcendence"
    volumes:
      - user-service-prisma-data:/usr/src/app/prisma
    ports:
      - "9229:9229"
      - "5555:5555"
    depends_on:
      - auth-service
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    environment:
      DATABASE_URL: "file:/usr/src/app/prisma/auth.db"
      JWT_SECRET: "transcendence"
      GOOGLE_CLIENT_ID: "298539346397-imm2ctlgievdlfb7vff3pdsh2291itjk.apps.googleusercontent.com"
    ports:
      - "3000:3000"
    volumes:
      - auth-prisma-data:/usr/src/app/prisma
    networks:
      - app-network

  game-service:
    build: game-service
    environment:
      DATABASE_URL: "file:/usr/src/app/prisma/game.db"
      JWT_SECRET: "transcendence"
    ports:
      - "3001:3001"
    volumes:
      - game-service-prisma-data:/usr/src/app/prisma
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user-service-prisma-data:
  auth-prisma-data:
  game-service-prisma-data: