services:
  backend: #django
    container_name: backend
    build:
      context: backend/
    command: python3 backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db: #postgres
    container_name: db
    image: postgres
    env_file:
      - .env
    environment:
      - "DATABASE=postgres"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_HOST=db"
      - "DB_PORT=5432"
    volumes:
      - db-volume:/var/lib/postgresql/data/
    restart: always
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  frontend:
    container_name: frontend
    build:
      context: frontend/
    ports:
      - "3000:80"

networks:
  network:
    driver: bridge

volumes:
  db-volume:
