name: CI/CD pipeline
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    build-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/checkout@v4
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: |
                  cd auth-service && npm ci
                  cd ../user-service && npm ci
                  cd ../game-service && npm ci
                  cd ../frontend && npm ci

#            - name: Run linting
#              run: |
#                  cd auth-service && npm run lint
#                  cd ../user-service && npm run lint
#                  cd ../game-service && npm run lint

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build services
              run: docker compose build

            - name: Start services
              run: docker compose up -d

            - name: Check if services are running
              run: docker compose ps

            - name: Docker compose down
              if: always()
              run: docker compose down -v