name: workflow.yml
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/checkout@v4
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: |
                  cd auth-service && npm ci
                  cd ../user-service && npm ci
                  cd ../game-service && npm ci
                  cd ../frontend && npm ci

            - name: Run linting
              run: |
                  cd auth-service && npm run lint
                  cd ../user-service && npm run lint
                  cd ../game-service && npm run lint

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker compose build and up
              run: docker-compose up --build -d

            - name: Docker compose down
              if: always()
              run: docker-compose down